services:
  ip-locations:
    build:
      context: .
    ports:
      - 5100:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Mongo__ConnectionString: "mongodb://crezcoAdmin:very_secure_password@mongodb:27017"
      Mongo__DatabaseName: "TestTest_Docker"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: crezcoAdmin
      MONGO_INITDB_ROOT_PASSWORD: very_secure_password

  dbui:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: crezcoAdmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: very_secure_password
    depends_on:
      - mongodb